# обычно в файле secrets.yml хранятся различные данные, чувствительные к утечке,
# например данные авторизации или платежной системы. Поэтому, такие файлы всегда
# стараются включать в .gitignore чтобы они ни в коем случае не попали в историю
# изменения объектов репозитория. Но для нашего примера сделаем исключение и
# зададим в таком файле параметры авторизации для админки
auth:
  login: "admin"
  pass: "123456"
